config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :items

devise_for :users, :controllers => {

  :omniauth_callbacks => 'users/omniauth_callbacks',
  :sessions => 'users/sessions',
  :registrations => 'users/registrations'
}
  resources :users
  root 'homes#index'

  resources :users do
    member do
      put 'follow'    => 'users#follow'
      put 'unfollow'    => 'users#unfollow'
    end
  end


  resources :homes do
    member do
      put 'poll_first'    => 'abouts#poll_first', as: 'poll_first'
      put 'poll_second'    => 'abouts#poll_second', as: 'poll_second'
      put 'poll_third'    => 'abouts#poll_third', as: 'poll_third'
      put 'poll_four'    => 'abouts#poll_four', as: 'poll_four'

    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :omniauthable, :recoverable, :registerable, :rememberable, :trackable, :validatable

acts_as_follower
acts_as_followable
mount_uploader :line, ImagesUploader

def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        username:     auth.info.nickname,
        avatar:     auth.info.image,
        uid:      auth.uid,
        provider: auth.provider,
        token: auth.credentials.token,
        secret: auth.credentials.secret,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user

  end


  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     puts "fewfewfewfewfewfewfewfewfewfewfewfew"
   end

  def update_resource(resource, params)
 resource.update_without_password(params)
end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @userid = current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    @userid = current_user
    @follow_status = {'status' => true}
    @user = User.find(params[:id])
    puts @userid.follows?(@user)
    if @userid.follows?(@user)
    unless About.find_by(["my_id = ? and user_id = ?", current_user, @user]).blank?
    About.find_by(["my_id = ? and user_id = ?", current_user, @user]).delete
    end
    current_user.unfollow!(@user)

    else
    current_user.follow!(@user)
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/follow.erb
	<% if current_user.follows?(@user) %> 
	$('.follow-btn').removeClass("unfollow");
	$('.follow-btn').addClass("follow");
	<% else %>	
	$('.follow-btn').removeClass("follow");
	$('.follow-btn').addClass("unfollow");
	<% end %>

	<% if current_user.follows?(@user) %> 
	$('.following-btn').removeClass("unfollow");
	$('.following-btn').addClass("follow");
	<% else %>	
	$('.following-btn').removeClass("follow");
	$('.following-btn').addClass("unfollow");
	<% end %>


	<% if current_user.follows?(@user) %> 
	$('.test').removeClass("about-u-select-hide");
	$('.test').addClass("about-u-select-show");
	<% else %>	
	$('.test').removeClass("about-u-select-show");
	$('.test').addClass("about-u-select-hide");
	<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
自分のマイページ

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="fri_user_page">

<div class="fri_user_page_image">
	<%= image_tag @user.avatar %>
</div>
<div class="fri_user_page_username">
<%= @user.username%>
</div>

</div>

 <% if @userid == @user %>
 <% elsif %>

                        <% if @userid.follows?(@user) %>

	                        <%= link_to follow_user_path, class:"following-btn",  :method => :put, remote: :true do %><span></span>
	                         <% end %>


			<div class="test about-u-select-show">

<% lovedatada = [] %>
  <% About.where(["my_id = ? and user_id = ? and about_id = ?", current_user.id, @user, 1]).each do |s| %>
      <%if @lo = About.find_by(["my_id = ? and user_id = ? and about_id = ?", s.user_id, current_user.id, 1]) %>
          <% lovedatada.push(User.find_by(id: @lo.my_id)) %>
      <% end %>
    <% end %>
    <% unless lovedatada == [] %>
			<% lovedatada.first(1).each do |dd| %>
			<p class="alert">両思いになりました。</p>
    <div class="lovemessage_box">
			<h3>LOVE LETTER</h3>
			<p><%= dd.lovemessage %></p>
    </div>
    <div class="line_box">
    	<h3>LINE</h3>
<center>
			<%= image_tag dd.line %>
</center>
	</div>
    	<% end %>


    <% end %>
    
				<% @user_id = params[:id] %>
				<% @my_id = current_user.id%>
			          	<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 1])%>
			             	<%= link_to poll_first_home_path(@user), method: :put do %>
			             	<li class="poll_1_checked">好きな人</li>
			             	<% end %>
			          	<% else %>
			             	<%= link_to poll_first_home_path(@user), method: :put do %>
			             	<li class="poll_1">好きな人</li>
			              	<% end %>
			          	<% end %>
				<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 2])%>
			              	<%= link_to poll_second_home_path(@user), method: :put do %>
			              	<li class="poll_2_checked">友達</li>
			              	<% end %>
			          	<% else %>
			            	<%= link_to poll_second_home_path(@user), method: :put do %>
			            	<li class="poll_2">友達</li>
			            	<% end %>
			          	<% end %>
				<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 3])%>
			              	<%= link_to poll_third_home_path(@user), method: :put do %>
			              	<li class="poll_3_checked">知り合い</li>
			              	<% end %>
			          	<% else %>
				             <%= link_to poll_third_home_path(@user), method: :put do %>
				             <li class="poll_3">知り合い</li>
				             <% end %>
			          	<% end %>
			  	<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 4])%>
				              <%= link_to poll_four_home_path(@user), method: :put do %>
				              <li class="poll_4_checked">家族</li>
				              <% end %>
			         	 <% else %>
				              <%= link_to poll_four_home_path(@user), method: :put do %>
				              <li class="poll_4">家族</li>
				              <% end %>
			          	<% end %>
 			</div>

		<% else %>

			<%= link_to follow_user_path, class:"follow-btn",  :method => :put, remote: :true do %><span></span>
			<% end %>

			<div class="test about-u-select-hide">
				<% @user_id = params[:id] %>
				<% @my_id = current_user.id%>
			          	<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 1])%>
			             	<%= link_to poll_first_home_path(@user), method: :put do %>
			             	<li class="poll_1_checked">好きな人_true</li>
			             	<% end %>
			          	<% else %>
			             	<%= link_to poll_first_home_path(@user), method: :put do %>
			             	<li class="poll_1">好きな人</li>
			              	<% end %>
			          	<% end %>
				<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 2])%>
			              	<%= link_to poll_second_home_path(@user), method: :put do %>
			              	<li class="poll_2_checked">親友_true</li>
			              	<% end %>
			          	<% else %>
			            	<%= link_to poll_second_home_path(@user), method: :put do %>
			            	<li class="poll_2">親友</li>
			            	<% end %>
			          	<% end %>
				<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 3])%>
			              	<%= link_to poll_third_home_path(@user), method: :put do %>
			              	<li class="poll_3_checked">ただの友達_true</li>
			              	<% end %>
			          	<% else %>
				             <%= link_to poll_third_home_path(@user), method: :put do %>
				             <li class="poll_3">ただの友達</li>
				             <% end %>
			          	<% end %>
			  	<% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", @my_id, @user.id, 4])%>
				              <%= link_to poll_four_home_path(@user), method: :put do %>
				              <li class="poll_4_checked">知り合い_true</li>
				              <% end %>
			         	 <% else %>
				              <%= link_to poll_four_home_path(@user), method: :put do %>
				              <li class="poll_4">知り合い</li>
				              <% end %>
			          	<% end %>
 			</div>

                     	<% end %>

<% end %>