config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :items

devise_for :users, :controllers => {

  :omniauth_callbacks => 'users/omniauth_callbacks',
  :sessions => 'users/sessions',
  :registrations => 'users/registrations'
}
  resources :users
  root 'homes#index'

  resources :users do
    member do
      put 'follow'    => 'users#follow'
      put 'unfollow'    => 'users#unfollow'
    end
  end


  resources :homes do
    member do
      put 'poll_first'    => 'abouts#poll_first', as: 'poll_first'
      put 'poll_second'    => 'abouts#poll_second', as: 'poll_second'
      put 'poll_third'    => 'abouts#poll_third', as: 'poll_third'
      put 'poll_four'    => 'abouts#poll_four', as: 'poll_four'

    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
	records_with_operator_on :create, :update
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
require "date"

  # GET /homes
  # GET /homes.json

  def index
    @homes = Home.all
    @users = User.all
    @sign_in_check = user_signed_in?

    if @sign_in_check
        @following_user = current_user.followees(@users)
        @follower_user = current_user.followers(@users)
    end

    @myfiend = Friend.where(:my_user_id => current_user.id)
    @myfriend_pluck = @myfiend.pluck(:friend_name)
    @myfiend_user = User.where(:username => @myfriend_pluck)

  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new

    @items = Item.all
    @possible_item_list = []
    @items.each do |test|
      if test.item_number > test.item_active_number
        @possible_item_list.push(test.item_name)
      end
    end

  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save

        @item = Item.find_by(:item_name => @home.home_item_name)
        @item.item_active_number += @home.home_item_number
        @item.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
        @home.home_item_days_start = Date.today
        @home.home_item_days_end = Date.today + @home.home_item_days

    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy

        @item = Item.find_by(:item_name => @home.home_item_name)
        @item.item_active_number -= @home.home_item_number
        @item.save

    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:home_item_name, :home_item_number, :home_item_request_teacher, :home_item_request_assistant, :home_item_days, :home_item_days_start, :home_item_days_end )
    end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<% lovedatada = [] %>

<% @myfiend_user.each do |boting|%>
  <% About.where(["my_id = ? and user_id = ? and about_id = ?", current_user.id, boting.id, 1]).each do |s| %>
      <%if @lo = About.find_by(["my_id = ? and user_id = ? and about_id = ?", s.user_id, current_user.id, 1]) %>
          <% lovedatada.push(User.find_by(id: @lo.my_id)) %>
      <% end %>
    <% end %>
    <% end %>
    <% unless lovedatada == [] %>
  <div class="love_data">
   <% lovedatada.each do |te|%>
    <%= link_to te do %>
    <div class="love_data_ava">
    <%= image_tag te.avatar %>
    </div>

    <p class="mese">
    <%= te.username %> さんから<br />
    あなたに LOVE LETTER が届いています。
   </p>
    <% end %>
   <% end %>
   </div>
   <% end %>

<% if @myfiend == [] %>
<%
    require "twitter" 
    client = Twitter::REST::Client.new do |config|
    config.consumer_key = "HJR6eT9S8AQPi5EI9FATav3GT"
    config.consumer_secret = "2bKpH1MwJ7ZyUKAq6g80LI0peEQTaIV7iRLctANpGRIXQF77CG"
    config.access_token = current_user.token
    config.access_token_secret = current_user.secret
  end
  %>

<% @followingUser = client.friends %>
<% @followingUser.map do |follower| %>
      <% @banana = Friend.new %>
      <% @banana.my_user_id = current_user.id %>
      <% @banana.friend_name = follower.screen_name%>
      <% @banana.friend_name_u = follower.name%>
      <% @banana.friend_id = follower.id %>
      <% @banana.friend_avatar = follower.profile_image_url %>
      <% @banana.save%>

<% end %>

<% else %>

<ul class="friend_list">
<% Friend.where(my_user_id: current_user.id).order(friend_check: :asc).each do |te|%>
<li>

  <% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 1])%>
        <div class="s_icon"><%= image_tag(asset_path "lbutton.png") %></div>
          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 2])%>
         <div class="s_icon"><%= image_tag(asset_path "fbutton.png") %></div>
          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 3])%>
         <div class="s_icon"><%= image_tag(asset_path "obutton.png") %></div>
          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 4])%>
         <div class="s_icon"><%= image_tag(asset_path "fabutton.png") %></div>

          <% else %>

          <% end %>

<div class="profile_image_friend"><%= image_tag te.friend_avatar%></div>
<div class="profile_name"><%= te.friend_name_u %></div>
<div class="profile_name_id">@<%= te.friend_name %></div>
<% if te.friend_check == true %>
  <div class="profile_score">

          <% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 1])%>
          <%= link_to "好きな人" ,  User.find_by(:username => te.friend_name) , :class => "score_button_1" %>

          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 2])%>
          <%= link_to "友達" ,  User.find_by(:username => te.friend_name) , :class => "score_button_2" %>

          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 3])%>
          <%= link_to "知り合い" ,  User.find_by(:username => te.friend_name) , :class => "score_button_3" %>

          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, User.find_by(:username => te.friend_name), 4])%>
          <%= link_to "家族" ,  User.find_by(:username => te.friend_name) , :class => "score_button_4" %>
          <% else %>
          <%= link_to "未選択" ,  User.find_by(:username => te.friend_name) , :class => "score_button_0" %>
          <% end %>

        </div>

          

<% end %>
<% if User.find_by(:username => te.friend_name).blank? == false %>
  <% te.friend_check = true %>
  <% te.save %>
<% end %>

</li>
<% end %>
</ul>

<!-- 
<ul class="friend_list">
<% @myfiend_user.each do |boting|%>
<li>
<div class="profile_image_friend"><%= image_tag boting.avatar%></div>
<%= link_to boting.username, boting  , :class => "profile_name" %>
        <div class="profile_score">
          <% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, boting.id, 1])%>
          <%= link_to "好きな人" , boting , :class => "score_button_1" %>
          <% end %>

          <% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, boting.id, 2])%>
          <%= link_to "親友" , boting , :class => "score_button_2" %>
          <% end %>

          <% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, boting.id, 3])%>
          <%= link_to "友達" , boting , :class => "score_button_3" %>
          <% end %>

          <% if About.find_by(["my_id = ? and user_id = ? and about_id = ?", current_user.id, boting.id, 4])%>
          <%= link_to "知り合い" , boting , :class => "score_button_4" %>
          <% end %>
        </div>

          <% if About.find_by(["my_id = ? and user_id = ? and about_id = ?",current_user.id,boting.id, 1]) && About.find_by(["my_id = ? and user_id = ? and about_id = ?",boting.id,current_user.id, 1])%>
          💕
          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?",current_user.id,boting.id, 1]) && About.find_by(["my_id = ? and user_id = ? and about_id = ?",boting.id,current_user.id, 2])%>
          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?",current_user.id,boting.id, 1]) && About.find_by(["my_id = ? and user_id = ? and about_id = ?",boting.id,current_user.id, 3])%>

          <% elsif About.find_by(["my_id = ? and user_id = ? and about_id = ?",current_user.id,boting.id, 1]) && About.find_by(["my_id = ? and user_id = ? and about_id = ?",boting.id,current_user.id, 3])%>

         <% end %>

<% end %>



</li>
</ul> -->
<% end %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home item name:</strong>
  <%= @home.home_item_name %>
</p>

<p>
  <strong>Home item number:</strong>
  <%= @home.home_item_number %>
</p>

<p>
  <strong>Home item request:</strong>
  <%= @home.home_item_request_teacher %>
</p>

<p>
  <strong>Home item request:</strong>
  <%= @home.home_item_request_assistant %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>